- name:
  hosts: elastic
  become: yes
  gather_facts: true

  tasks:
  - name:
    apt:
      deb: "https://mirror.g-soft.info/elasticsearch/elasticsearch-8.17.1-amd64.deb"

  - name: 
    copy:
      src: /home/user/ansible/elastic_conf.yml
      dest: /etc/elasticsearch/elasticsearch.yml

  - name: daemon_reload
    systemd:
      daemon_reload: true

  - name:
    service:
      name: elasticsearch
      state: restarted
      enabled: yes
