---
- name: 
  hosts: elastic_srv
  become: yes
  gather_facts: true

  tasks:
  - name: 
    get_url:
      url: "https://mirror.yandex.ru/mirrors/elastic/7/pool/main/e/elasticsearch/elasticsearch-7.15.1-amd64.deb"
      dest: /tmp/elasticsearch-7.15.1-amd64.deb
      mode: '0644'

  - name: 
    apt:
      deb: /tmp/elasticsearch-7.15.1-amd64.deb
      state: present  

  - name: 
    copy:
      src: /home/user/ansible/elastic_conf.yml
      dest: /etc/elasticsearch/elasticsearch.yml
      owner: elasticsearch 
      group: elasticsearch 
      mode: '0644' 

  - name: 
    sysctl:
      name: vm.max_map_count
      value: "262144"
      state: present
      reload: yes 

  - name: daemon_reload
    systemd:
      daemon_reload: true

  - name: 
    service:
      name: elasticsearch
      state: restarted
      enabled: yes
