---
- name:
  hosts: kibana
  become: yes
  vars:
    elastic_httphost: "10.1.0.40:9200"
  tasks:

  - name: 
    apt:
      deb: "https://mirror.g-soft.info/kibana/kibana-8.17.1-amd64.deb"

  - name: 
    template:
      src: /home/ubuntu/ansible/kibana.j2
      dest: /etc/kibana/kibana.yml

  - name: daemon_reload
    systemd:
      daemon_reload: true

  - name: 
    service:
      name: kibana
      state: restarted
      enabled: yes
