---
- hosts: kibana_servers
  become: true  
  vars:
    kibana_version: "8.11.3"
    elasticsearch_hosts: ["http://10.1.0.40:9200", "http://89.169.134.21:9200"]
    kibana_system_password: "{{ lookup('env', 'KIBANA_SYSTEM_PASSWORD') }}"
  
    saved_objects_encryption_key: "0c1d1e2e3f4a5b6c7d8e9fa0b1c2d3e4f5a6b7c8d9e0fa1b2c3d4e5f6a7b8c9d"
    server_host: "0.0.0.0"
    server_port: 5601

  tasks:
    - name:
      apt:
        name:
          - apt-transport-https
          - ca-certificates
        state: present
        update_cache: yes

    - name:
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name:
      apt_repository:
        repo: "deb https://artifacts.elastic.co/packages/{{ kibana_version.split('.')[0] }}.x/apt stable main"
        state: present
        filename: elastic

    - name:
      apt:
        name: kibana={{ kibana_version }}
        state: present
        update_cache: yes

    - name:
      template:
        src: templates/kibana.yml.j2
        dest: /etc/kibana/kibana.yml
        owner: kibana
        group: kibana
        mode: 0644
      notify: restart_kibana

    - name:
      systemd:
        name: kibana
        enabled: yes
        state: started

  handlers:
    - name:
      systemd:
        name: kibana
        state: restarted
