---
- name: Add Elasticsearch GPG key
  become: true
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present

- name: Add Elasticsearch repository
  become: true
  apt_repository:
    repo: "deb https://mirror.g-soft.info/elasticsearch/elasticsearch-8.17.1-amd64.deb stable main"
    state: present
    filename: elasticsearch

- name: Install Elasticsearch package
  become: true
  apt:
    name: elasticsearch
    state: present
    update_cache: yes

- name: Create Elasticsearch configuration directory
  become: true
  file:
    path: /etc/elasticsearch
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: "0755"

- name: Copy Elasticsearch configuration file
  become: true
  template:
    src: "elasticsearch.yml.j2"
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: elasticsearch
    group: elasticsearch
    mode: "0644"
  notify: Restart Elasticsearch

- name: Copy JVM options file
  become: true
  template:
    src: "jvm.options.j2"
    dest: /etc/elasticsearch/jvm.options
    owner: elasticsearch
    group: elasticsearch
    mode: "0644"
  notify: Restart Elasticsearch

- name: Ensure Elasticsearch is running and enabled
  become: true
  systemd:
    name: elasticsearch
    state: started
    enabled: yes
