- name: Установка Zabbix
  hosts: zabbix
  become: true
  vars:
    pass_zabbixdb: zabbix

  tasks:
    - name: 
      shell: wget https://repo.zabbix.com/zabbix/7.2/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.2+ubuntu24.04_all.deb
      args:
        chdir: /tmp

    - name: 
      shell: dpkg -i zabbix-release_latest_7.2+ubuntu24.04_all.deb
      args:
        chdir: /tmp

    - name: 
      apt:
        update_cache: yes

    - name: 
      apt:
        name:
          - apache2
          - postgresql
          - postgresql-contrib
          - python3-pexpect
          - python3-pip
          - python3-dev
          - python3-venv
          - python3-psycopg2
          - zabbix-server-pgsql
          - zabbix-frontend-php
          - php8.2-pgsql
          - zabbix-apache-conf
          - zabbix-sql-scripts
          - zabbix-agent
        state: present

    - name: 
      ansible.builtin.expect:
        command: sudo -u postgres createuser --pwprompt zabbix
        responses:
          (?i).*(Enter password for new role)(.*):
           - '{{ pass_zabbixdb }}'
          (?i).*(Enter it again)(.*):
           - '{{ pass_zabbixdb }}'

    - name: 
      shell: >
        sudo -u postgres createdb -O zabbix zabbix

    - name: 
      shell:
        zcat /usr/share/zabbix/sql-scripts/postgresql/server.sql.gz | sudo -u zabbix psql zabbix

    - name: 
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: '^DBPassword='
        line: 'DBPassword=zabbix'
        
    - name: Перезапуск служб Zabbix
      service:
        name: "{{ item }}"
        state: restarted
        enabled: yes
        
      loop:
        - zabbix-server
        - zabbix-agent
        - apache2
